import "./main.css";
import todoFactory from "./app/todoFactory";
import projectFactory from "./app/projectFactory";
import projectsUI from "./app/projectsUI";

const domEle = document.createElement("div");
domEle.textContent = "Hello, world!";
domEle.classList.add("element");
document.querySelector("body").appendChild(domEle);
// console.log(projects);
// project1.add();
// project1.add();
// project1.add();
// console.log(project1.getList().todo[0].getTitle());
// console.log(project1.getList().todo[0].setTitle("kup mleko"));
// console.log(project1.getList().todo[0].getTitle());
// const todo1 = project1.getList().todo[0];
// console.log(todo1.getDeadlineDate());
// todo1.setDeadlineDate(new Date(2023, 0, 18));
// console.log(todo1.getDeadlineDate());
// todo1.setTitle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
projectsUI.add();
projectsUI.add();
console.log(projectsUI.getProjects);
const projects = projectsUI.getProjects;
projects[0].getTodoUI.add();
projects[0].getTodoUI.add();
projects[0].getTodoUI.add();
console.log(projects[0].getTodoUI.getList());
