import "./main.css";

import projectsUI from "./app/projectsUI";

const domEle = document.createElement("div");
domEle.textContent = "Hello, world!";
domEle.classList.add("element");
document.querySelector("body").appendChild(domEle);
// console.log(projects);
// project1.add();
// project1.add();
// project1.add();
// console.log(project1.getList().todo[0].getTitle());
// console.log(project1.getList().todo[0].setTitle("kup mleko"));
// console.log(project1.getList().todo[0].getTitle());
// const todo1 = project1.getList().todo[0];
// console.log(todo1.getDeadlineDate());
// todo1.setDeadlineDate(new Date(2023, 0, 18));
// console.log(todo1.getDeadlineDate());
// todo1.setTitle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
projectsUI.add();
projectsUI.add();
console.log(projectsUI.getProjects);
const projects = projectsUI.getProjects;
projects[0].todoUI.add();
projects[0].todoUI.add();
projects[0].todoUI.add();
console.log(projects[0].todoUI.getList());
projects[1].todoUI.add();
projects[1].todoUI.add();
console.log(projects[0].todoUI.getList());
console.log(projects[1].todoUI.getList());
projects[1].todoUI.setPriority(0, 1);
projects[1].todoUI.setPriority(1, 2);
console.log(projects[1].todoUI.getList()[0].getPriority());
console.log(projects[1].todoUI.getList()[1].getPriority());
projects[1].todoUI.setStatus(0, 1);
projects[1].todoUI.setStatus(1, 2);
console.log(projects[1].todoUI.getList()[0].getStatus());
console.log(projects[1].todoUI.getList()[1].getStatus());
console.log(projects[1].todoUI.getList());

projects[1].todoUI.remove(0);
console.log(projects[1].todoUI.getList());
